rotateMatrix: rotateMatrix.c rotate.c rotate.h
	gcc -o rotateMatrix -std=gnu99 -Wall -Werror rotateMatrix.c rotate.c

debugRotate: rotateMatrix.c rotate.c rotate.h
	gcc -o debugRotate -ggdb3 -std=gnu99 -Wall -Werror rotateMatrix.c rotate.c